Update Episerver packages, enable Multitargeting
episerver/content-search-lucene pull request #23
Opened 2023-03-19 15:31 UTC by karolberezicki

Hi 🙂 

In this PR I would like to bring following changes to `content-search-lucene`:
* Bring `Episerver` dependencies up to latest versions (`12.13.1`/`12.17.1`)
* Enable multitargeting to `.NET 6` and `.NET 7`
* Set `ContentCacheScope` for `IndexingJob` to reduce memory consumption for larger project
* Set SDK to 7.0
* Build Docker image with .NET 7 by default
* Minor updates to test packages

I plan to bring more memory optimizations also for data collecting in `IndexingJob` / `ContentSearchHandlerImplementation` , but in a separate PR, if this will be approved and merged.

2023-03-23 16:24 UTC, lunchin commented
The cla is now enabled on this repo, please sign the cla for us to be able to except your pull requests

2023-03-23 16:32 UTC, lunchin requested changes

2023-03-23 16:32 UTC, lunchin commented on Directory.Build.props
> +    <TargetFrameworks>net6.0;net7.0</TargetFrameworks>
We are not specifically targeting standard releases moving forward just LTS.  We test to make sure package can run on latest but do update target frameworks

2023-03-23 16:32 UTC, lunchin commented on src/EPiServer.Search.Cms/EPiServer.Search.Cms.csproj
> +    <TargetFrameworks>net6.0;net7.0</TargetFrameworks>
Keep at 6

2023-03-23 16:32 UTC, lunchin commented on src/EPiServer.Search.Cms/EPiServer.Search.Cms.csproj
> +    <PackageReference Include="EPiServer.CMS.UI.Core" Version="12.9.3" />
Should use dependency versions from props file

2023-03-23 16:32 UTC, lunchin commented on src/EPiServer.Search.Cms/EPiServer.Search.Cms.csproj
> +    <PackageReference Include="EPiServer.CMS.AspNetCore.Templating" Version="12.13.2"  />
Should use dependency versions from props file

2023-03-23 16:32 UTC, lunchin commented on src/EPiServer.Search.IndexingService/EPiServer.Search.IndexingService.csproj
> +    <TargetFrameworks>net6.0;net7.0</TargetFrameworks>
Just target 7 for the container app

2023-03-25 19:02 UTC, karolberezicki commented
Thank you for the review @lunchin, much appreciated :) 
I've retargeted the packages and framework versions according to the comments.

2023-04-12 16:39 UTC, lunchin approved these changes

2023-04-12 18:58 UTC, lunchin commented
create new pr to fix build issues on fork

2023-04-12 18:58 UTC, closed without merging